// <auto-generated />
namespace DataAcess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditKeyWord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditKeyWord));
        
        string IMigrationMetadata.Id
        {
            get { return "202011132057004_EditKeyWord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
